"""
PROJECT: CIGOL
TOOL:    VAULT BUILDER (The Wrapper)
AUTHOR:  Ben Creizy


DESCRIPTION:
This script takes any Python source file and 'wraps' it in a layer of 
AES-256 encryption. It generates a new, secure version of the file that 
executes purely in memory. The source code is never exposed on the disk 
of the target machine.
"""


import sys
import os
import base64
try:
    from cryptography.fernet import Fernet
except ImportError:
    print("[ ERROR ] You need the 'cryptography' library.")
    print("[ FIX   ] Run: pip install cryptography")
    sys.exit(1)


def create_secure_wrapper(target_file):
    if not os.path.exists(target_file):
        print(f"[ ERROR ] File '{target_file}' not found.")
        return


    # 1. GENERATE A FRESH KEY
    # This key is unique to this specific build.
    key = Fernet.generate_key()
    cipher_suite = Fernet(key)


    # 2. READ THE RAW CODE
    with open(target_file, 'rb') as f:
        raw_code = f.read()


    # 3. ENCRYPT THE CODE
    encrypted_data = cipher_suite.encrypt(raw_code)


    # 4. CONSTRUCT THE LOADER
    # This is the code that will live inside the secure file.
    # It acts as a bio-shell, holding the encrypted DNA and unlocking it only at runtime.
    
    loader_code = f"""# WRAPPED SECURE FILE - GENERATED BY VAULT BUILDER
# DO NOT EDIT THIS FILE. EDITING BREAKS THE INTEGRITY CHECK.


import sys
import base64
try:
    from cryptography.fernet import Fernet
except ImportError:
    raise ImportError("Security Wrapper requires 'cryptography' library.")


# --- THE KEY ---
# (NOTE: In a production environment, this key should be loaded from 
# environment variables, but for a standalone repo, we embed it here 
# to ensure the script runs for the authorized user.)
_K = {key}


# --- THE PAYLOAD ---
_P = {encrypted_data}


def _ignite():
    try:
        # Decrypt directly to memory
        f = Fernet(_K)
        decrypted_logic = f.decrypt(_P)
        
        # Execute the logic in the current global namespace.
        # This allows functions/classes to be imported by other scripts.
        exec(decrypted_logic, globals())
        
    except Exception as e:
        print("[ SECURITY ] INTEGRITY BREACH DETECTED.")
        sys.exit(1)


# Ignite the payload immediately upon import
_ignite()
"""


    # 5. WRITE THE SECURE FILE
    output_filename = target_file.replace('.py', '_secure.py')
    with open(output_filename, 'w') as f:
        f.write(loader_code)


    print(f"\n[ SUCCESS ] File wrapped successfully.")
    print(f"[ SOURCE  ] {target_file}")
    print(f"[ OUTPUT  ] {output_filename}")
    print(f"[ ADVICE  ] Rename '{output_filename}' to '{target_file}' before pushing.")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python vault_builder.py <file_to_wrap.py>")
    else:
        create_secure_wrapper(sys.argv[1])